# Site wide configuration

title:            byroni.us
locale:           en_US
url:


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Byron Wall
  avatar: byron-wall.jpg
  bio: "Avid programmer and chemical engineer in Denver, CO"
  email: byron@byroni.us
  disqus-shortname:
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-63893175-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: byronwall
  stackoverflow: 4288101/byron-wall
  linkedin: byronwall
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  kaggle: byronwall

#prose config
prose:
  rooturl:
  siteurl: 'http://byroni.us'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "text"
          label: "layout"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "category"
        field:
          element: "text"
          label: "category"
          value: "blog"


include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
